.TH DROBOM "8" "October 2008" "droboa " "System Administration Utilities"
.SH NAME
drobom \- CLI for managing drobo units
.SH SYNOPSIS
.B drobom
[ \fIoptions\fR ] \fI<command> \fR[ \fIarguments\fR... ]
.SH DESCRIPTION
.SS "options is one of:"
.TP
-c, --command
the command to execute.
.TP
-d, --device
the device to operate on (default searches all devices and picks first one found.)
.TP
-v, --verbose
verbosity, a bit-field to trigger increased output as needed, mostly for debugging. 
1 - General, 2 - Hardware Dialog, 4 - Initiation, 8 - DMP layer, 16- Detection
255 will print everything... (default: 0, as terse as possible.)
.TP
-h, --help
print a usage message
.SS "command is one of:"
.TP
blink
identify the drobo by making the lights blink
.TP
diag
dump diagnostics file into /tmp directory
.TP
fwcheck query drobo.com for updates to firmware for the given Drobo
fwload  load a specific firmware for the given Drobo. Arguments:
.sp
.br
<fwimage>
the firmware file to load.
.TP
fwupgrade
upgrade the firmware to the latest and greatest, recommended by DRI
.TP
help
print this text
.TP
info
print all available information on a Drobo
.TP
list
show device files for all Drobos found.
.IP
settime sync Drobo's clock to UTC
setlunsize  Set the size of LUNS on device. Arguments:
.sp
<sz>
integer number of TiB to set the lunsize to
.sp
<confirmation>
Specify 'PleaseEraseMyData' if you really mean it
.sp
Note: After execution, Drobo reboots, wait a few minutes before accessing again
.TP
shutdown
shutdown drobo (DRI calls this 'standby' ... umount first!)
.TP
status
report how is the Drobo doing
.SS
device
raw block device of a drobo. If not given, it will be searched for.
.SH AUTHOR
This manual page was written by Chris AtLee <chris@atlee.ca> for the Debian
project (but may be used by others).
