.TH DROBOVIEW "16" "October 2009" "droboview" "System Administration Utilities"
.SH NAME
droboview \- GUI for managing data robotics (drobo) storage units
.SH SYNOPSIS
.B droboview
\fR[ \fI<device> \fR]
.SH DESCRIPTION
Starts the graphical management utility for Drobos. See drobom for detailed
usage. (this is the same as the 'drobom view')
.TP
.I device
raw block device of a drobo. If not given, it will be searched for.
.SH SEE ALSO
drobom(8)
.SH AUTHOR
This manual page was written by Chris AtLee <chris@atlee.ca> for the Debian
project (but may be used by others).
