Document: droboutils
Title: Debian droboutils Manual
Author: <insert document author here>
Abstract: This manual describes what droboutils is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/droboutils/droboutils.sgml.gz

Format: postscript
Files: /usr/share/doc/droboutils/droboutils.ps.gz

Format: text
Files: /usr/share/doc/droboutils/droboutils.text.gz

Format: HTML
Index: /usr/share/doc/droboutils/html/index.html
Files: /usr/share/doc/droboutils/html/*.html

  
