#!/bin/sh
set -e
# Automatically added by dh_pycentral
if which pycentral >/dev/null 2>&1 && pycentral --help 2>/dev/null | grep -q pkgprepare; then
	pycentral pkgprepare droboutils <<PYEOF
[python-package]
format = 1
python-version = 2.5
[pycentral]
version = 0.6.1
[files]
/usr/lib/python2.5/site-packages/Drobo.py=f
/usr/lib/python2.5/site-packages/DroboGUI.py=f
/usr/lib/python2.5/site-packages/DroboDMP.so=f
/usr/lib/python2.5/site-packages/Drobo_utils-1.0.egg-info=f
PYEOF
else
	mkdir -p /var/lib/pycentral
	echo droboutils >> /var/lib/pycentral/delayed-pkgs
fi
# End automatically added section
